services:
  - type: web
    name: wisor-ai-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: BCRYPT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: ./uploads
      - key: LOG_LEVEL
        value: info
      - key: ANTHROPIC_API_KEY
        sync: false  # This will need to be set manually in Render dashboard
      - key: SERP_API_KEY
        sync: false  # Optional - for web search functionality
    healthCheckPath: /health
    autoDeploy: true