[build]
  publish = "dist"
  command = "mkdir -p dist && cp public/index.html dist/ && cp assets/favicon.png dist/ && cp public/_redirects dist/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"