[build]
  publish = "dist"
  command = "mkdir -p dist && cp public/index.html dist/ && cp assets/favicon.png dist/ && cp public/_redirects dist/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"