[build]
  publish = "public"
  command = "cd wisor-web-app && npm install && npm run build && npm run export && cp -r out/* ../public/app/"

[[redirects]]
  from = "/app/*"
  to = "/app/:splat"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_PUBLIC_SUPABASE_URL = "https://gpqdzgfnkepeexdgtrda.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcWR6Z2Zua2VwZWV4ZGd0cmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjAxOTgsImV4cCI6MjA3NDUzNjE5OH0.4iOn2YvvBREMPOF-NHk3X3t2OxgPrz9gm2UJVg3RapU"
  NEXTAUTH_SECRET = "k8m9n2p5q7r1s4t6u8v0w3x5y7z2a4b6c8d1e3f5g7h9"
  NEXT_PUBLIC_APP_URL = "https://new-age-los.netlify.app"
  
# Enhanced Wisor Credit Optimizer v2.0 - Features Added:
# ✅ User-added cards with dynamic reward fetching  
# ✅ Auto-updating rewards on amount changes
# ✅ Real-time offer scraping from major websites
# 🤖 AI-powered recommendations with offer context