[build]
  publish = "dist"
  command = "echo 'Using pre-built dist files'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"