services:
  # Frontend Landing Page
  - type: web
    name: wisor-landing-page
    runtime: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production